server:
  port: 8888
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://111.231.144.209:3306/oop?useUnicode=true&characterEncoding=utf8
    username: root
    password: heyan
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update